/* Generated by Yosys 0.63+87 (git sha1 2f1cdc2df, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:2.1-12.10" *)
module counter(clk, rst, en, \count[0] , \count[1] );
  (* src = "counter.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "counter.v:5.11-5.13" *)
  input en;
  wire en;
  (* src = "counter.v:6.22-6.27" *)
  output \count[0] ;
  wire \count[0] ;
  (* src = "counter.v:6.22-6.27" *)
  output \count[1] ;
  wire \count[1] ;
  (* src = "counter.v:10.27-10.39" *)
  wire _00_;
  (* src = "counter.v:10.27-10.39" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "counter.v:8.3-11.6" *)
  DFF _06_ (
    .C(clk),
    .D(_03_),
    .Q(\count[0] )
  );
  (* src = "counter.v:8.3-11.6" *)
  DFF _07_ (
    .C(clk),
    .D(_05_),
    .Q(\count[1] )
  );
  assign _02_ = en ? _00_ : \count[0] ;
  assign _04_ = en ? _01_ : \count[1] ;
  assign _03_ = rst ? 1'h0 : _02_;
  assign _05_ = rst ? 1'h0 : _04_;
  assign _00_ = ~\count[0] ;
  assign _01_ = \count[1]  ^(* src = "counter.v:10.27-10.39|/home/zhugy/.oss-cad-suite/lib/../share/yosys/techmap.v:296.13-296.25" *)  \count[0] ;
endmodule
