ps2_code = {
    "Escape": "0x76",
    "F1": "0x05",
    "F2": "0x06",
    "F3": "0x04",
    "F4": "0x0C",
    "F5": "0x03",
    "F6": "0x0B",
    "F7": "0x83",
    "F8": "0x0A",
    "F9": "0x01",
    "F10": "0x09",
    "F11": "0x78",
    "F12": "0x07",
    "Backquote": "0x0E",
    "Digit1": "0x16",
    "Digit2": "0x1E",
    "Digit3": "0x26",
    "Digit4": "0x25",
    "Digit5": "0x2E",
    "Digit6": "0x36",
    "Digit7": "0x3D",
    "Digit8": "0x3E",
    "Digit9": "0x46",
    "Digit0": "0x45",
    "Minus": "0x4E",
    "Equal": "0x55",
    "KeyA": "0x1C",
    "KeyB": "0x32",
    "KeyC": "0x21",
    "KeyD": "0x23",
    "KeyE": "0x24",
    "KeyF": "0x2B",
    "KeyG": "0x34",
    "KeyH": "0x33",
    "KeyI": "0x43",
    "KeyJ": "0x3B",
    "KeyK": "0x42",
    "KeyL": "0x4B",
    "KeyM": "0x3A",
    "KeyN": "0x31",
    "KeyO": "0x44",
    "KeyP": "0x4D",
    "KeyQ": "0x15",
    "KeyR": "0x2D",
    "KeyS": "0x1B",
    "KeyT": "0x2C",
    "KeyU": "0x3C",
    "KeyV": "0x2A",
    "KeyW": "0x1D",
    "KeyX": "0x22",
    "KeyY": "0x35",
    "KeyZ": "0x1A",
    "BracketLeft": "0x54",
    "BracketRight": "0x5B",
    "Backslash": "0x5D",
    "Semicolon": "0x4C",
    "Quote": "0x52",
    "Enter": "0x5A",
    "Comma": "0x41",
    "Period": "0x49",
    "Slash": "0x4A",
    "Tab": "0x0D",
    "Space": "0x29",
    "Backspace": "0x66",
}

key_mapping = {
    "Backquote": ("`", "~"),
    "Digit1": ("1", "!"),
    "Digit2": ("2", "@"),
    "Digit3": ("3", "#"),
    "Digit4": ("4", "$"),
    "Digit5": ("5", "%"),
    "Digit6": ("6", "^"),
    "Digit7": ("7", "&"),
    "Digit8": ("8", "*"),
    "Digit9": ("9", "("),
    "Digit0": ("0", ")"),
    "Minus": ("-", "_"),
    "Equal": ("=", "+"),
    "KeyA": ("a", "A"),
    "KeyB": ("b", "B"),
    "KeyC": ("c", "C"),
    "KeyD": ("d", "D"),
    "KeyE": ("e", "E"),
    "KeyF": ("f", "F"),
    "KeyG": ("g", "G"),
    "KeyH": ("h", "H"),
    "KeyI": ("i", "I"),
    "KeyJ": ("j", "J"),
    "KeyK": ("k", "K"),
    "KeyL": ("l", "L"),
    "KeyM": ("m", "M"),
    "KeyN": ("n", "N"),
    "KeyO": ("o", "O"),
    "KeyP": ("p", "P"),
    "KeyQ": ("q", "Q"),
    "KeyR": ("r", "R"),
    "KeyS": ("s", "S"),
    "KeyT": ("t", "T"),
    "KeyU": ("u", "U"),
    "KeyV": ("v", "V"),
    "KeyW": ("w", "W"),
    "KeyX": ("x", "X"),
    "KeyY": ("y", "Y"),
    "KeyZ": ("z", "Z"),
    "BracketLeft": ("[", "{"),
    "BracketRight": ("]", "}"),
    "Backslash": ("\\", "|"),
    "Semicolon": (";", ":"),
    "Quote": ("'", '"'),
    "Comma": (",", "<"),
    "Period": (".", ">"),
    "Slash": ("/", "?"),
    "Space": (" ", " "),
    "Tab": ("\t", "\t"),
    "Backspace": ("\b", "\b"),
    "Enter": ("\n", "\n"),
}


def bin_str(number):
    return format(number, "b").upper().zfill(8)


result_bin_upper = []
result_bin_lower = []


for key, value in ps2_code.items():
    if key in key_mapping:
        ps2_hex = bin_str(int(value, 16))
        lower_char, upper_char = key_mapping[key]
        lower_hex = bin_str(ord(lower_char))
        upper_hex = bin_str(ord(upper_char))
        result_bin_lower.append(f"17'b0{ps2_hex}{lower_hex}")
        result_bin_upper.append(f"17'b1{ps2_hex}{upper_hex}")

print(",\n".join(result_bin_lower + result_bin_upper))
