key_to_ps2code = {
    "Escape": b"\x76",
    "F1": b"\x05",
    "F2": b"\x06",
    "F3": b"\x04",
    "F4": b"\x0c",
    "F5": b"\x03",
    "F6": b"\x0b",
    "F7": b"\x83",
    "F8": b"\x0a",
    "F9": b"\x01",
    "F10": b"\x09",
    "F11": b"\x78",
    "F12": b"\x07",
    "Backquote": b"\x0e",
    "Digit1": b"\x16",
    "Digit2": b"\x1e",
    "Digit3": b"\x26",
    "Digit4": b"\x25",
    "Digit5": b"\x2e",
    "Digit6": b"\x36",
    "Digit7": b"\x3d",
    "Digit8": b"\x3e",
    "Digit9": b"\x46",
    "Digit0": b"\x45",
    "Minus": b"\x4e",
    "Equal": b"\x55",
    "Backslash": b"\x5d",
    "Backspace": b"\x66",
    "Tab": b"\x0d",
    "KeyQ": b"\x15",
    "KeyW": b"\x1d",
    "KeyE": b"\x24",
    "KeyR": b"\x2d",
    "KeyT": b"\x2c",
    "KeyY": b"\x35",
    "KeyU": b"\x3c",
    "KeyI": b"\x43",
    "KeyO": b"\x44",
    "KeyP": b"\x4d",
    "BracketLeft": b"\x54",
    "BracketRight": b"\x5b",
    "Capslock": b"\x58",
    "KeyA": b"\x1c",
    "KeyS": b"\x1b",
    "KeyD": b"\x23",
    "KeyF": b"\x2b",
    "KeyG": b"\x34",
    "KeyH": b"\x33",
    "KeyJ": b"\x3b",
    "KeyK": b"\x42",
    "KeyL": b"\x4b",
    "Semicolon": b"\x4c",
    "Quote": b"\x52",
    "Enter": b"\x5a",
    "LShift": b"\x12",
    "KeyZ": b"\x1a",
    "KeyX": b"\x22",
    "KeyC": b"\x21",
    "KeyV": b"\x2a",
    "KeyB": b"\x32",
    "KeyN": b"\x31",
    "KeyM": b"\x3a",
    "Comma": b"\x41",
    "Period": b"\x49",
    "Slash": b"\x4a",
    "RShift": b"\x59",
    "LCtrl": b"\x14",
    "LAlt": b"\x11",
    "Space": b"\x29",
    "RAlt": b"\x11\xe0",
    "RCtrl": b"\x14\xe0",
    "Ins": b"\x70\xe0",
    "Home": b"\x6c\xe0",
    "PUp": b"\x7d\xe0",
    "Del": b"\x71\xe0",
    "End": b"\x69\xe0",
    "PDn": b"\x7a\xe0",
    "Up": b"\x75\xe0",
    "Left": b"\x6b\xe0",
    "Down": b"\x72\xe0",
    "Right": b"\x74\xe0",
    "SmallNum": b"\x77",
    "SmallDiv": b"\x4a\xe0",
    "SmallMul": b"\x7c",
    "SmallSub": b"\x7b",
    "SmallAdd": b"\x79",
    "SmallEnter": b"\x5a\xe0",
    "SmallDot": b"\x71",
    "Small0": b"\x70",
    "Small1": b"\x69",
    "Small2": b"\x72",
    "Small3": b"\x7a",
    "Small4": b"\x6b",
    "Small5": b"\x73",
    "Small6": b"\x74",
    "Small7": b"\x6c",
    "Small8": b"\x75",
    "Small9": b"\x7d",
}

kay_to_ascii = {
    "Backquote": ("`", "~"),
    "Digit1": ("1", "!"),
    "Digit2": ("2", "@"),
    "Digit3": ("3", "#"),
    "Digit4": ("4", "$"),
    "Digit5": ("5", "%"),
    "Digit6": ("6", "^"),
    "Digit7": ("7", "&"),
    "Digit8": ("8", "*"),
    "Digit9": ("9", "("),
    "Digit0": ("0", ")"),
    "Minus": ("-", "_"),
    "Equal": ("=", "+"),
    "Backslash": ("\\", "|"),
    "Backspace": ("\b", "\b"),
    "Tab": ("\t", "\t"),
    "KeyQ": ("q", "Q"),
    "KeyW": ("w", "W"),
    "KeyE": ("e", "E"),
    "KeyR": ("r", "R"),
    "KeyT": ("t", "T"),
    "KeyY": ("y", "Y"),
    "KeyU": ("u", "U"),
    "KeyI": ("i", "I"),
    "KeyO": ("o", "O"),
    "KeyP": ("p", "P"),
    "BracketLeft": ("[", "{"),
    "BracketRight": ("]", "}"),
    "KeyA": ("a", "A"),
    "KeyS": ("s", "S"),
    "KeyD": ("d", "D"),
    "KeyF": ("f", "F"),
    "KeyG": ("g", "G"),
    "KeyH": ("h", "H"),
    "KeyJ": ("j", "J"),
    "KeyK": ("k", "K"),
    "KeyL": ("l", "L"),
    "Semicolon": (";", ":"),
    "Quote": ("'", '"'),
    "Enter": ("\n", "\n"),
    "KeyZ": ("z", "Z"),
    "KeyX": ("x", "X"),
    "KeyC": ("c", "C"),
    "KeyV": ("v", "V"),
    "KeyB": ("b", "B"),
    "KeyN": ("n", "N"),
    "KeyM": ("m", "M"),
    "Comma": (",", "<"),
    "Period": (".", ">"),
    "Slash": ("/", "?"),
    "Space": (" ", " "),
    "SmallDiv": ("/", "/"),
    "SmallMul": ("*", "*"),
    "SmallSub": ("-", "-"),
    "SmallAdd": ("+", "+"),
    "SmallEnter": ("\n", "\n"),
    "SmallDot": (".", "."),
    "Small0": ("0", "0"),
    "Small1": ("1", "1"),
    "Small2": ("2", "2"),
    "Small3": ("3", "3"),
    "Small4": ("4", "4"),
    "Small5": ("5", "5"),
    "Small6": ("6", "6"),
    "Small7": ("7", "7"),
    "Small8": ("8", "8"),
    "Small9": ("9", "9"),
}

for key, ps2code in key_to_ps2code.items():
    if key in kay_to_ascii:
        ps2_is_ext = 1 if len(ps2code) == 2 else 0
        lower_char, upper_char = kay_to_ascii[key]
        lower_ascii = ord(lower_char)
        upper_ascii = ord(upper_char)
        print(f"{{1'b0,1'b{ps2_is_ext},8'd{ps2code[0]},8'd{lower_ascii}}},")
        print(f"{{1'b1,1'b{ps2_is_ext},8'd{ps2code[0]},8'd{upper_ascii}}},")
